export const TransactionActionTypes = {
  FETCH_TRANSACTIONS_START: 'FETCH_TRANSACTIONS_START',
  FETCH_TRANSACTIONS_SUCCESS: 'FETCH_TRANSACTIONS_SUCCESS',
  FETCH_TRANSACTIONS_FAILURE: 'FETCH_TRANSACTIONS_FAILURE',

  GET_TRANSACTION_START: 'GET_TRANSACTION_START',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILURE: 'GET_TRANSACTION_FAILURE',

  TRANSACTION_SEARCH_START: 'TRANSACTION_SEARCH_START',
  TRANSACTION_SET_SEARCH_RESULT: 'TRANSACTION_SET_SEARCH_RESULT',

  CLEAN_TRANSACTIONS: 'CLEAN_TRANSACTIONS'
};
