export const OrganizationActionTypes = {
  FETCH_ORGANIZATIONS_START: 'FETCH_ORGANIZATIONS_START',
  FETCH_ORGANIZATIONS_SUCCESS: 'FETCH_ORGANIZATIONS_SUCCESS',
  FETCH_ORGANIZATIONS_FAILURE: 'FETCH_ORGANIZATIONS_FAILURE',

  GET_ORGANIZATION: 'GET_ORGANIZATION',
  SET_ORGANIZATION: 'SET_ORGANIZATION',

  ORGANIZATION_SEARCH_START: 'ORGANIZATION_SEARCH_START',
  ORGANIZATION_SET_SEARCH_RESULT: 'ORGANIZATION_SET_SEARCH_RESULT'
};
