export const AgentActionTypes = {
  FETCH_AGENTS_START: 'FETCH_AGENTS_START',
  FETCH_AGENTS_SUCCESS: 'FETCH_AGENTS_SUCCESS',
  FETCH_AGENTS_FAILURE: 'FETCH_AGENTS_FAILURE',

  GET_AGENT: 'GET_AGENT',
  SET_AGENT: 'SET_USER',

  AGENT_SEARCH_START: 'AGENT_SEARCH_START',
  AGENT_SET_SEARCH_RESULT: 'AGENT_SET_SEARCH_RESULT'
};
