export const CustomerActionTypes = {
  FETCH_CUSTOMERS_START: 'FETCH_CUSTOMERS_START',
  FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',

  GET_CUSTOMER: 'GET_CUSTOMER',
  SET_CUSTOMER: 'SET_CUSTOMER',

  CUSTOMER_SEARCH_START: 'CUSTOMER_SEARCH_START',
  CUSTOMER_SET_SEARCH_RESULT: 'CUSTOMER_SET_SEARCH_RESULT'
};
